AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lab-aws-2024-porteiro

  Sample SAM Template for lab-aws-2024-porteiro
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  LigarPorteiro:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: handlers/porteiro.startEC2Instances
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        CloudWatchEvent:
          Type: Schedule 
          Properties:
            Schedule: cron(50, 10 ?, * MON-FRI *)
      Policies: 
        - Statement:
          - Sid: StartEC2
            Effect: Allow
            Action:
              - ec2:StartInstances
            Resource: '*'
  DesligarPorteiro:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: handlers/porteiro.stopEC2Instances
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        CloudWatchEvent:
          Type: Schedule 
          Properties:
            Schedule: cron(50, 20 ?, * MON-FRI *)
      Policies: 
        - Statement:
          - Sid: StartEC2
            Effect: Allow
            Action:
              - ec2:StopInstances
            Resource: '*'