version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gameofthrones
      POSTGRES_USER: jonsnow
      POSTGRES_PASSWORD: winteriscoming
    volumes:
      - '${PWD}/pg-data:/var/lib/postgresql/data'
